flowchart TD
    Start([User: getCurrentTransactionCounter<br/>call])
    Start --> CheckInit{TSE<br/>initialized?}
    
    CheckInit -->|No| ErrorInit[Exception:<br/>ErrorDeviceNotInitialized]
    CheckInit -->|Yes| GetCounter[SM: Get current<br/>transaction counter]
    
    GetCounter --> CheckGet{Retrieval<br/>successful?}
    
    CheckGet -->|No| ErrorGet[Exception:<br/>ErrorGetTransactionCounterFailed]
    CheckGet -->|Yes| Return[Return:<br/>transactionCounter]
    
    Return --> End([End])
    
    ErrorInit --> End
    ErrorGet --> End
    
    style GetCounter fill:#87CEEB
    style Return fill:#90EE90
    
    Note1[Note: The transaction counter<br/>is incremented with each<br/>startTransaction]
    GetCounter -.-> Note1
    
    Note2[Usage:<br/>- Check number of transactions<br/>- Plausibility check<br/>- Monitoring]
    Return -.-> Note2
